<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LigaFutbol [
    <!ELEMENT LigaFutbol (Partido*)>
    <!ELEMENT Partido (equipoLocal, equipoVisitante)>
    <!ELEMENT equipoLocal (nombre)>
    <!ELEMENT equipoVisitante (nombre)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT goles (#PCDATA)>

    <!ATTLIST equipoLocal goles CDATA #REQUIRED>
    <!ATTLIST equipoVisitante goles CDATA #REQUIRED>
]>
<LigaFutbol>
    <Partido>
        <equipoLocal goles="0">
            <nombre>Equipo A</nombre>
        </equipoLocal>
        <equipoVisitante goles="0">
            <nombre>Equipo B</nombre>
        </equipoVisitante>
    </Partido>
</LigaFutbol>